version: "3.8"
services:
  backend:
    build:
      context: ./Zalo_App_BE
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Zalo_Clone_FE
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
